version: '3.8'
services:
  go:
    build:
      context: .
      dockerfile: ./build/docker/go/dockerfile
    ports:
      - "9000:9000" # Web Server
    volumes:
      - ./:/app
    environment:
      PORT: "9000"
  postgres:
    build:
      context: .
      dockerfile: ./build/docker/postgres/dockerfile
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  postgres:
    driver: local